services:
  client:
    build: .
    container_name: client

    environment:
      - OLLAMA_HOST=http://localhost:11434/api/generate
      - AI_SERVER_URL=https://hackathon-rough-sunset-2856.fly.dev

    command:
      - --input
      - /app/files/input
      - --output
      - /app/files/output

    volumes:
      - ./files/input:/app/files/input
      - ./files/output:/app/files/output
